"""empty message

Revision ID: 41659ef6ac4a
Revises: 63e901a66c09
Create Date: 2025-11-02 11:12:55.864719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41659ef6ac4a'
down_revision = '63e901a66c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
